import { describe, expect, it } from 'vitest';

import { getAllPosts, getPostBySlug } from '@/lib/content';

import { findH } from './findH';

describe('MDX table of contents', () => {
  it('excludes a shell comment inside a fenced code block', () => {
    const post = getPostBySlug('nextjs-blog/nextjs-markdown')!;
    const slugs = findH(post.body.raw).map(item => item.slug);

    expect(slugs).not.toContain('our-project');
    expect(slugs).toContain('markdown-적용하기');
  });

  it('uses the generated heading ID for an underscore in source Markdown', () => {
    const post = getPostBySlug('solo-project/solo3')!;
    const slugs = findH(post.body.raw).map(item => item.slug);

    expect(slugs).toContain('base_url-설정하기');
    expect(slugs).not.toContain('baseurl-설정하기');
  });

  it('only links to heading IDs generated by Velite in every published post', () => {
    for (const post of getAllPosts()) {
      for (const heading of findH(post.body.raw)) {
        expect(
          post.body.code,
          `${post.url}: missing heading #${heading.slug}`,
        ).toContain(`id:${JSON.stringify(heading.slug)}`);
      }
    }
  });
});
