import { ProjectType } from '@/types/projectType';

export const projectObj: ProjectType[] = [
  {
    name: 'Solo Project Making Shoppig app',
    image: 'https://i.imgur.com/towbLSY.png',
    description: '북마크 기능이 있는 상품 리스트 페이지를 구현합니다.',
    href: 'https://kd02109.github.io/ShoppingApp',
    github: 'https://github.com/kd02109/ShoppingApp',
    link: 'solo-project',
    date: '2023-05-12 ~ 2023-05-18',
    stack: [
      'react',
      'typescript',
      'redux',
      'eslint',
      'vite',
      'reactRouter',
      'reactQuery',
    ],
  },
  {
    name: 'SharePetment',
    image: 'https://i.imgur.com/UjNDTNc.png',
    description:
      '반려동물의 일상을 함께 공유하는 SNS 및 산책 친구를 구하는 app입니다.',
    href: 'https://sharepetment.site/',
    github: 'https://github.com/SharePetment/SharePetment',
    link: 'sharepetment',
    date: '2023-06-28 ~ 2023-09-09',
    stack: [
      'typescript',
      'react',
      'tailwindcss',
      'eslint',
      'reactRouter',
      'reactQuery',
      'vite',
      'reactHookForm',
      'netlify',
    ],
  },
  {
    name: 'NextJS Blog',
    image: 'https://i.imgur.com/y7xcTyo.png',
    description: 'Next.js를 기반으로 한 개발 블로그를 구현합니다.',
    href: 'https://sonblog.vercel.app',
    github: 'https://github.com/kd02109/Nextjs-Blog',
    link: 'nextjs-blog',
    date: '2023-08-30 ~ 2023-09-20',
    stack: [
      'react',
      'typescript',
      'nextJs',
      'mdx',
      'contentlayer',
      'tailwindcss',
    ],
  },
  {
    name: 'Mbti Test Project',
    image: 'https://i.imgur.com/A7BAUbv.png',
    description:
      '기존의 O,X 선택지에서 벗어나 정확도가 높은 대화형 mbti web app 구현합니다.',
    href: 'https://mbtmi.xyz',
    github: 'https://github.com/kd02109/mbtmi',
    link: 'mbtmi',
    date: '2023-10-30 ~ 2023-12-21',
    stack: ['react', 'typescript', 'nextJs'],
  },
];
