create table if not exists public.views (
  id bigint generated by default as identity primary key,
  slug text not null,
  view_count bigint not null default 0
);

create unique index if not exists views_slug_key on public.views (slug);

update public.views
set view_count = 0
where view_count is null;

alter table public.views
  alter column view_count set default 0,
  alter column view_count set not null;

alter table public.views enable row level security;

do $migration$
declare
  existing_policy record;
begin
  for existing_policy in
    select policyname
    from pg_policies
    where schemaname = 'public' and tablename = 'views'
  loop
    execute format(
      'drop policy %I on public.views',
      existing_policy.policyname
    );
  end loop;
end
$migration$;

create policy views_public_select
on public.views
for select
to anon, authenticated
using (true);

revoke all on table public.views from public, anon, authenticated;
grant select on table public.views to anon, authenticated;

drop function if exists public.increment_view(text);

create function public.increment_view(slug_text text)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  next_view_count bigint;
begin
  if
    slug_text is null
    or length(slug_text) > 120
    or slug_text !~ '^[A-Za-z0-9]+(-[A-Za-z0-9]+)*$'
  then
    raise exception using
      errcode = '22023',
      message = 'invalid view slug';
  end if;

  insert into public.views as existing_view (slug, view_count)
  values (slug_text, 1)
  on conflict (slug) do update
    set view_count = coalesce(existing_view.view_count, 0) + 1
  returning view_count into next_view_count;

  return next_view_count;
end
$function$;

alter function public.increment_view(text) owner to postgres;

revoke all on function public.increment_view(text)
from public, anon, authenticated;
grant execute on function public.increment_view(text) to service_role;

do $migration$
begin
  if to_regprocedure('public.increment(text)') is not null then
    execute
      'revoke all on function public.increment(text) from public, anon, authenticated, service_role';
  end if;
end
$migration$;
