create table if not exists public.views (
  id bigint generated by default as identity primary key,
  slug text not null,
  view_count bigint not null default 0
);

create unique index if not exists views_slug_key on public.views (slug);

update public.views
set view_count = 0
where view_count is null;

alter table public.views
  alter column view_count set default 0,
  alter column view_count set not null;

alter table public.views enable row level security;

do $migration$
declare
  existing_policy record;
begin
  for existing_policy in
    select policyname
    from pg_policies
    where schemaname = 'public' and tablename = 'views'
  loop
    execute format(
      'drop policy %I on public.views',
      existing_policy.policyname
    );
  end loop;
end
$migration$;

create policy views_public_select
on public.views
for select
to anon, authenticated
using (true);

revoke all on table public.views from public, anon, authenticated;
grant select on table public.views to anon, authenticated;

create schema if not exists private;

revoke all on schema private from public, anon, authenticated;

create table if not exists private.view_events (
  slug text not null references public.views (slug) on delete cascade,
  visitor_hash text not null check (visitor_hash ~ '^[0-9a-f]{64}$'),
  viewed_on date not null default ((current_timestamp at time zone 'UTC')::date),
  primary key (slug, visitor_hash, viewed_on)
);

alter table private.view_events enable row level security;

do $migration$
declare
  existing_policy record;
begin
  for existing_policy in
    select policyname
    from pg_policies
    where schemaname = 'private' and tablename = 'view_events'
  loop
    execute format(
      'drop policy %I on private.view_events',
      existing_policy.policyname
    );
  end loop;
end
$migration$;

revoke all on table private.view_events
from public, anon, authenticated, service_role;

drop function if exists public.increment_view(text);
drop function if exists public.increment_view(text, text);

create function public.increment_view(slug_text text, visitor_hash_text text)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  next_view_count bigint;
  recorded_view boolean;
begin
  if
    slug_text is null
    or length(slug_text) > 120
    or slug_text !~ '^[A-Za-z0-9]+(-[A-Za-z0-9]+)*$'
  then
    raise exception using
      errcode = '22023',
      message = 'invalid view slug';
  end if;

  if
    visitor_hash_text is null
    or visitor_hash_text !~ '^[0-9a-f]{64}$'
  then
    raise exception using
      errcode = '22023',
      message = 'invalid visitor hash';
  end if;

  insert into public.views as existing_view (slug, view_count)
  values (slug_text, 0)
  on conflict (slug) do nothing;

  insert into private.view_events (slug, visitor_hash, viewed_on)
  values (
    slug_text,
    visitor_hash_text,
    (current_timestamp at time zone 'UTC')::date
  )
  on conflict (slug, visitor_hash, viewed_on) do nothing
  returning true into recorded_view;

  if recorded_view is true then
    update public.views
    set view_count = view_count + 1
    where slug = slug_text
    returning view_count into next_view_count;
  else
    select view_count
    into next_view_count
    from public.views
    where slug = slug_text;
  end if;

  return next_view_count;
end
$function$;

alter function public.increment_view(text, text) owner to postgres;

revoke all on function public.increment_view(text, text)
from public, anon, authenticated;
grant execute on function public.increment_view(text, text) to service_role;

do $migration$
begin
  if to_regprocedure('public.increment(text)') is not null then
    execute
      'revoke all on function public.increment(text) from public, anon, authenticated, service_role';
  end if;
end
$migration$;
